name: Release on tag

on:
  push:
    tags:
      - "v*.*.*"   # v1.0.1 のようなセマンティックバージョンで動く

permissions:
  contents: write   # リリース作成に必要

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ここでビルドや成果物作成が必要なら追加（今回は無し）

      - name: Create GitHub Release (auto notes)
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
